snippets:
  - name: "cd there"
    keyword: "CD"
    snippet: "&& cd $_"
    context:
      lbuffer: '.+\s'

  - name: "copy"
    keyword: "CC"
    snippet: "| pbcopy"
    context:
      lbuffer: '.+\s'

  - name: "grep"
    keyword: "G"
    snippet: "| grep"
    context:
      lbuffer: '.+\s'

  - name: "null"
    keyword: "NULL"
    snippet: ">/dev/null 2>&1"
    context:
      lbuffer: '.+\s'

  - name: "nom build"
    keyword: "nb"
    snippet: ", nom build"

  - name: "nom shell"
    keyword: "ns"
    snippet: ", nom shell"

  - name: "nom develop"
    keyword: "nd"
    snippet: ", nom develop"
