name: test
on:
  - push
jobs:
  amd64:
    name: amd64
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dotfiles
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S --template "email=email@example.com" --template "name=example".
