name: Build

on:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - "flake.lock"
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read
    outputs:
      nix: ${{ steps.filter.outputs.nix }}
    steps:
      - name: Filter changed paths
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            nix:
              - "**.nix"
              - "flake.lock"

  build:
    needs: changes
    if: github.event_name != 'pull_request' || needs.changes.outputs.nix == 'true'
    runs-on: macos-15
    timeout-minutes: 600
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35

      - name: Setup Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: airrnot
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
          skipPush: ${{ github.event_name == 'pull_request' }}

      - name: Build devShell
        run: nix develop --show-trace -c true

      - name: Build darwinConfigurations
        run: nix build --show-trace --no-link .#darwinConfigurations.macbook-air-m5.system

      - name: Print disk usage
        run: df -h
