name: Build

on:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - "flake.lock"
  pull_request:
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      nix: ${{ steps.filter.outputs.nix }}
    steps:
      - name: Filter changed paths
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            nix:
              - "**.nix"
              - "flake.lock"

  build:
    needs: changes
    if: github.event_name != 'pull_request' || needs.changes.outputs.nix == 'true'
    runs-on: macos-15
    timeout-minutes: 600
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.event_name == 'pull_request' }}

      - name: Build devShell
        run: nix develop --show-trace -c true

      - name: Build darwinConfigurations
        run: nix build --show-trace --no-link .#darwinConfigurations.macbook-air-m2.system

      - name: Print disk usage
        run: df -h
